window.touch=function(){function c(b){if("undefined"!==typeof registeredKeycodes[b.keyCode])for(var a=0;a<registeredKeycodes[b.keyCode].length;++a)registeredActions[registeredKeycodes[b.keyCode][a]].a(1),b.preventDefault()}function a(b){if("undefined"!==typeof registeredKeycodes[b.keyCode])for(var a=0;a<registeredKeycodes[b.keyCode].length;++a)registeredActions[registeredKeycodes[b.keyCode][a]].a(0),b.preventDefault()}function e(b,a){var d,c;c=[];for(var h=0;h<rectangles.length;++h){d=rectangles[h];
var e=d[0],g=d[1];e>=b+0||e+d[2]<=b||g>=a+0||g+d[3]<=a||c.push(d[4])}return c}function d(b){for(var a=0;a<b.length;++a)"undefined"!==typeof registeredActions[b[a]]&&registeredActions[b[a]].a(1)}function f(b){b.preventDefault();var a=b.targetTouches,c,h,l;for(c=0;c<a.length;++c){b=a[c];g.getBoundingClientRect();h=b.pageX-window.pageXOffset-g.offsetLeft;l=b.pageY-window.pageYOffset-g.offsetTop;l=e(h,l);for(h=0;h<l.length;++h)0>registeredActions[l[c]].touches.indexOf(b.identifier)&&(registeredActions[l[c]].touches[registeredActions[l[c]].touches.length]=
b.identifier);d(l)}}function b(b){b.preventDefault();b=b.changedTouches;var a,d;for(a=0;a<b.length;++a)for(d in registeredActions);}function h(b){b.preventDefault();var a=g.getBoundingClientRect();b=e(b.clientX-a.left,b.clientY-a.top);d(b);for(a=0;a<b.length;++a)mouseActions.push(b[a])}function l(b){for(b.preventDefault();0<mouseActions.length;)registeredActions[mouseActions[0]].a(0),mouseActions.splice(0,1)}var g;registeredActions={};rectangles=[];mouseActions=[];registeredKeycodes={};return{init:function(d){g=
d;g.removeEventListener("mousedown",h);g.removeEventListener("mouseup",l);g.removeEventListener("touchstart",f,!1);g.removeEventListener("touchleave",b,!1);g.removeEventListener("touchend",b,!1);g.removeEventListener("touchcancel",b,!1);document.removeEventListener("keydown",c);document.removeEventListener("keyup",a);g.addEventListener("mousedown",h,!1);g.addEventListener("mouseup",l,!1);g.addEventListener("touchstart",f,!1);g.addEventListener("touchleave",b,!1);g.addEventListener("touchend",b,!1);
g.addEventListener("touchcancel",b,!1);document.addEventListener("keydown",c);document.addEventListener("keyup",a)},UP:0,DOWN:1,registerAction:function(b,a,d){"undefined"!==typeof a&&null!==a&&(a[4]=b,rectangles.push(a));registeredActions[b]={rect:a,a:b,i:d,touches:[]};if(null!==d)for(a=0;a<d.length;++a)void 0===registeredKeycodes[d[a]]?registeredKeycodes[d[a]]=[b]:registeredKeycodes[d[a]].push(b)},unregisterActions:function(b){for(var a=rectangles.length;0<=a;--a)rectangles[a][4]===b&&rectangles.splice(a,
1);for(var d,c=registeredActions[b].i,a=0;a<c.length;++a)d=registeredKeycodes[c[a]].indexOf(b),0<=d&&(registeredKeycodes[c[a]]=registeredKeycodes[c[a]].splice(d,1));delete registeredActions[b]},keydownListener:c,keyupListener:a,getActions:e,touchStartMoveListener:f,touchEndCancelListener:b,mouseDownListener:h,mouseUpListener:l}}();window.D=function(){var c,a,e;return{setCanvas:function(a){c=a},enableDepthTest:function(d){d?a.enable(a.DEPTH_TEST):a.disable(a.DEPTH_TEST)},enableBlend:function(d){d?a.enable(a.BLEND):a.disable(a.BLEND)},usePremultipliedAlphaBlending:function(d){d?a.blendFunc(a.ONE,a.ONE_MINUS_SRC_ALPHA):a.blendFunc(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA)},init:function(){a=c.getContext("webgl")||c.getContext("experimental-webgl");window.addEventListener("resize",function f(){c.width=c.clientWidth;c.height=c.clientHeight;
a.viewport(0,0,c.clientWidth,c.clientHeight);return f}());a.enable(a.DEPTH_TEST);a.enable(a.CULL_FACE);a.depthFunc(a.LEQUAL);a.frontFace(a.CW)},setShaderProgram:function(a){e=a},createShader:function(d,c){function b(b,a,d){b.shaderSource(a,d);b.compileShader(a);return b.getShaderParameter(a,b.COMPILE_STATUS)?a:(console.log(b.getShaderInfoLog(a)),null)}var h=a.createShader(a.VERTEX_SHADER),e=a.createShader(a.FRAGMENT_SHADER);if(!b(a,h,d))return console.log("(vshader)"),null;if(!b(a,e,c))return console.log("(fshader)"),
null;var g=a.createProgram();a.attachShader(g,h);a.attachShader(g,e);a.linkProgram(g);if(!a.getProgramParameter(g,a.LINK_STATUS))return console.log("Shader init failed."),null;a.useProgram(g);return g},clear:function(d){"undefined"===typeof d&&(d={r:.2,h:.2,f:.3,c:1});a.clearColor(d.r,d.h,d.f,d.c);a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT)},draw:function(d,c){d.texture.set();var b=a.getAttribLocation(e,"vertPos");a.bindBuffer(a.ARRAY_BUFFER,d.vertBuffer);a.enableVertexAttribArray(b);a.vertexAttribPointer(b,
3,a.FLOAT,!1,0,0);b=a.getAttribLocation(e,"texCoord");a.bindBuffer(a.ARRAY_BUFFER,d.texCoord);a.enableVertexAttribArray(b);a.vertexAttribPointer(b,2,a.FLOAT,!1,0,0);b=a.getUniformLocation(e,"matrix");a.uniformMatrix4fv(b,!1,d.matrix);b=a.getUniformLocation(e,"textureTransform");a.uniformMatrix4fv(b,!1,d.textureMatrix);b=a.getUniformLocation(e,"perspective");"undefined"===typeof c&&(c=mat.create());a.uniformMatrix4fv(b,!1,c);a.drawArrays(a.TRIANGLES,0,6)},createTexture:function(d){d.texture=a.createTexture();
d.set=function(){a.bindTexture(a.TEXTURE_2D,d.texture)};a.bindTexture(a.TEXTURE_2D,d.texture);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,d.image)},createTexturedSquare:function(d,c){var b=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,b);a.bufferData(a.ARRAY_BUFFER,
new Float32Array([0,0,0,1,0,0,0,1,0,1,0,0,1,1,0,0,1,0]),a.STATIC_DRAW);var h=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h);a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,1,0,0,1,1,0,1,1,0,1]),a.STATIC_DRAW);return{vertBuffer:b,texCoord:h,texture:c,matrix:d,textureMatrix:mat.create()}},createSquare:function(d){var c=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c);a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,0,1,0,0,0,1,0,1,0,0,1,1,0,0,1,0]),a.STATIC_DRAW);var b=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,
b);a.bufferData(a.ARRAY_BUFFER,new Float32Array([1,0,0,1,1,0,1,0,1,1,1,0,0,1,1,1,0,1]),a.STATIC_DRAW);return{vertBuffer:c,colorBuffer:b,matrix:d}}}}();window.mat=function(){function c(b){return"undefined"===typeof b||null===b||16!==b.length?a([]):d(b)}function a(b){b[0]=1;b[1]=0;b[2]=0;b[3]=0;b[4]=0;b[5]=1;b[6]=0;b[7]=0;b[8]=0;b[9]=0;b[10]=1;b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b}function e(b,a,c){var d,e,f,m;for(d=0;4>d;++d)for(e=0;4>e;++e){for(f=m=0;4>f;++f)m+=b[d+4*f]*a[f+4*e];c[d+4*e]=m}return c}function d(b,a){"undefined"===typeof a?a=[]:a.splice(0,a.length);b.some(function(b,d){if(16<=d)return!0;a.push(b)});return a}var f={create:c,
transpose:function(b){b[1]=b[4];b[2]=b[8];b[3]=b[12];b[4]=b[1];b[6]=b[9];b[7]=b[13];b[8]=b[2];b[9]=b[6];b[11]=b[14];b[12]=b[3];b[13]=b[7];b[14]=b[11];return b},identity:a,scale:function(b,a,d,c){b[0]=a;b[1]=0;b[2]=0;b[3]=0;b[4]=0;b[5]=d;b[6]=0;b[7]=0;b[8]=0;b[9]=0;b[10]=c;b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},rotateX:function(b,a){b[0]=1;b[1]=0;b[2]=0;b[3]=0;b[4]=0;b[5]=Math.cos(a);b[6]=-Math.sin(a);b[7]=0;b[8]=0;b[9]=Math.sin(a);b[10]=Math.cos(a);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=
1;return b},rotateY:function(b,a){b[0]=Math.cos(a);b[1]=0;b[2]=-Math.sin(a);b[3]=0;b[4]=0;b[5]=1;b[6]=0;b[7]=0;b[8]=Math.sin(a);b[9]=0;b[10]=Math.cos(a);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},rotateZ:function(b,a){b[0]=Math.cos(a);b[1]=-Math.sin(a);b[2]=0;b[3]=0;b[4]=Math.sin(a);b[5]=Math.cos(a);b[6]=0;b[7]=0;b[8]=0;b[9]=0;b[10]=1;b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},rotateAbout:function(b,a,d,c,e){var f=Math.sin(a);a=Math.cos(a);var m=d*c,E=f*e,F=d*e,G=f*c,H=c*e,f=f*d;b[0]=
a+(1-a)*d*d;b[1]=(1-a)*m+E;b[2]=(1-a)*F-G;b[3]=0;b[4]=(1-a)*m-E;b[5]=a+(1-a)*c*c;b[6]=(1-a)*H+f;b[7]=0;b[8]=(1-a)*F+G;b[9]=(1-a)*H-f;b[10]=a+(1-a)*e*e;b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},translate:function(a,d,c,e){a[0]=1;a[1]=0;a[2]=0;a[3]=d;a[4]=0;a[5]=1;a[6]=0;a[7]=c;a[8]=0;a[9]=0;a[10]=1;a[11]=e;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},multiplicate:e,copy:d,execute:function(b,h,l){"undefined"!==typeof l&&!0===l&&a(b);var g=c(b),C=c();h.forEach(function(a){d(g,b);f[a[0]](C,a[1],
a[2],a[3],a[4]);e(b,C,g)});return d(g,b)},perspective:function(a,d,c,e,f){f=1/(1/f)*Math.tan(d/2);a[0]=Math.tan(d/2);a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=f;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=-(e+c)/(c-e);a[11]=2*e*c/(c-e);a[12]=0;a[13]=0;a[14]=1;a[15]=0;return a}};return f}();var k=[];function n(){for(var c=k.length=0;16>c;++c)k.push([0,c]);for(c=0;3>c;++c)p(k,q(0,k))}n();var r;
(function(){D.setCanvas(document.getElementsByTagName("canvas")[0]);D.init();D.enableDepthTest(!1);D.enableBlend(!0);D.usePremultipliedAlphaBlending(!1);D.setShaderProgram(D.createShader(document.getElementById("vtexshader").firstChild.textContent,document.getElementById("ftexshader").firstChild.textContent));var c=2*function(){var a=document.createElement("canvas").getContext("2d");return(window.devicePixelRatio||1)/a.s||a.l||a.m||a.o||a.j||1}(),a=document.createElement("canvas");a.width=1024*c;
a.height=1024*c;var e=a.getContext("2d");e.setTransform(c,0,0,c,0,0);e.font="16px Arial";e.fillStyle="white";for(c=0;c<Math.log2(16384);++c)e.fillText(""+Math.pow(2,c+1),6+45.8*c,28);var d=new Image;d.src=a.toDataURL();d.onload=function(){touch.init(document.getElementsByTagName("body")[0]);touch.registerAction(function(a){a===touch.DOWN&&(t(u),v())},null,[37]);touch.registerAction(function(a){a===touch.DOWN&&(t(w),v())},null,[38]);touch.registerAction(function(a){a===touch.DOWN&&(t(x),v())},null,
[39]);touch.registerAction(function(a){a===touch.DOWN&&(t(y),v())},null,[40]);var a={image:d};D.createTexture(a);r=D.createTexturedSquare(mat.create(),a);z()}})();var A=[.5,.5],B={r:0,f:0,h:0,c:0};function z(){var c=0,a=0,e;for(D.clear(B);16>c;++c)e=[a*A[0]-1,-Math.floor(c/4)*A[1]+1],I(e,k[c][0]),++a,4<=a&&(a=0)}
function I(c,a){var e=A;0!==a&&(mat.execute(r.matrix,[["scale",e[0],-e[1],1],["translate",c[0],c[1],.5]],!0),mat.execute(r.textureMatrix,[["scale",45.8/1024,45.8/1024,1],["translate",45.8*(Math.log2(a)-1)/1024,0,0]],!0),D.draw(r,mat.create()))}var J=[];
function v(){for(var c=0,a=0,e=0,d=window.setInterval(function(){var a,c,f;if(0===J.length)window.clearInterval(d);else{D.clear(B);for(a=0;a<J.length;++a)c=J[a],f=1-e/.25,I([c.b[0]+(c.g[0]-c.b[0])*f,c.b[1]+(c.g[1]-c.b[1])*f],c.value);e+=.016;.25<=e&&(window.clearInterval(d),J.length=0,z())}},16),f;c<k.length;++c)0!==k[c][0]&&f!==c&&(f=k[c][1],J.push({b:[a*A[0]-1,-Math.floor(c/4)*A[1]+1],g:[f%4*A[0]-1,-Math.floor(f/4)*A[1]+1],value:k[c][0]})),++a,4<=a&&(a=0)}
function K(c,a){var e=[],d;if(a)for(d=0;4>d;++d)e.push(k[c+4*d]);else for(d=0;4>d;++d)e.push(k[4*c+d]);return e}function L(c,a,e){if(e)for(e=0;e<a.length;++e)k[c+a.length*e]=a[e];else for(e=0;e<a.length;++e)k[c*a.length+e]=a[e]}var u=0,w=1,x=2,y=3;
function t(c){for(var a=0,e=!1,d=0;d<k.length;++d)k[d][1]=d;switch(c){case u:for(;4>a;++a)d=K(a,!1),M(d)&&(e=!0),L(a,d,!1);break;case w:for(;4>a;++a)d=K(a,!0),M(d)&&(e=!0),L(a,d,!0);break;case x:for(;4>a;++a)d=K(a,!1).reverse(),M(d)&&(e=!0),L(a,d.reverse(),!1);break;case y:for(;4>a;++a)d=K(a,!0).reverse(),M(d)&&(e=!0),L(a,d.reverse(),!0)}a=q(0,k);0===a.length?(window.alert("You lost, loser!"),n()):e&&p(k,a,c)}
function M(c){function a(a){var d,g,f;for(d=b-1;d>=a;--d)if(0===c[d][0])for(g=d;g<b-1;++g)0!==c[g+1][0]&&(f=c[g],c[g]=c[g+1],c[g+1]=f,e=!0)}var e=!1,d=0,f=0,b=c.length;for(a(0);d<b-1;++d)if(c[d][0]===c[d+1][0]&&0!==c[d][0]){f=c[d];c[d]=c[d+1];c[d+1]=f;c[d][0]*=2;c[d+1][0]=0;f=c[d+1][1]=d;e=!0;break}a(f);return e}function q(c,a){for(var e=[],d=0;d<a.length;++d)a[d][0]===c&&e.push(d);return e}
function p(c,a,e){a=a.concat(q(2,c));a=a[Math.floor(0+Math.random()*(a.length-0))];c[a][0]+=2;if("undefined"===typeof e)c[a][1]=a;else switch(e){case u:c[a][1]=5*Math.floor(a/4);break;case x:c[a][1]=4*Math.floor(a/4);break;case w:c[a][1]=Math.floor(a%4)+12;break;case y:c[a][1]=Math.floor(a%4)}};
